---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/ADEX_experiment1_baseline_plots/ADEX_experiment1_baseline_plots.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/91025/articles/179547/master/file/figures/ADEX_experiment1_baseline_plots/ADEX_experiment1_baseline_plots.png"
    folder_url: "/users/91025/articles/179547/master/folder/figures/ADEX_experiment1_baseline_plots"
