---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - url: "/users/91025/articles/179547/master/file/figures/dynamic_segments1/dynamic_segments1.png"
    path: figures/dynamic_segments1/dynamic_segments1.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
