---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/sub_circuits2/sub_circuits2.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/91025/articles/179547/master/file/figures/sub_circuits2/sub_circuits2.png"
    folder_url: "/users/91025/articles/179547/master/folder/figures/sub_circuits2"
