---
version: 2
multicolumn: false
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/compartment_circuit_dynamics/compartment_circuit_dynamics.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/91025/articles/179547/master/file/figures/compartment_circuit_dynamics/compartment_circuit_dynamics.png"
    folder_url: "/users/91025/articles/179547/master/folder/figures/compartment_circuit_dynamics"
